export default COIN_LIST = [
  {
    id: 1,
    name: 'Bitcoin',
    unit: 'BTC',
    textColor: '#B57B14',
    backgroundColor: '#F0E8D1',
    image: require('../assets/images/crypto/bitcoin.png'),
    inactiveimage: require('../assets/images/crypto/bitcoinInactive.png'),
    avatar: require('../assets/images/avatars/boy2.png'),
    price: '55728.00',
    priceDown: false,
  },

  {
    id: 2,
    name: 'Litecoin',
    unit: 'LTC',
    textColor: '#1437B5',
    backgroundColor: '#D1E3F0',
    image: require('../assets/images/crypto/litecoin.png'),
    inactiveimage: require('../assets/images/crypto/litecoinInactive.png'),
    avatar: require('../assets/images/avatars/girl2.png'),
    price: '55728.00',
    priceDown: true,
  },

  {
    id: 3,
    name: 'Tron',
    unit: 'TRX',
    textColor: '#6B0505',
    backgroundColor: '#E7D0D0',
    image: require('../assets/images/crypto/tron.png'),
    inactiveimage: require('../assets/images/crypto/tronInactive.png'),
    avatar: require('../assets/images/avatars/boy3.png'),
    price: '55728.00',
    priceDown: false,
  },
  {
    id: 4,
    name: 'Tether',
    unit: 'USDT',
    textColor: '#056B39',
    backgroundColor: '#D0E7DE',
    image: require('../assets/images/crypto/tether.png'),
    inactiveimage: require('../assets/images/crypto/tetherInactive.png'),
    avatar: require('../assets/images/avatars/girl2.png'),
    price: '55728.00',
    priceDown: true,
  },

  {
    id: 5,
    name: 'Binance Coin',
    unit: 'BNB',
    textColor: '#B57B14',
    backgroundColor: '#F0E8D1',
    image: require('../assets/images/crypto/binance.png'),
    inactiveimage: require('../assets/images/crypto/binanceInactive.png'),
    avatar: require('../assets/images/avatars/girl3.png'),
    price: '55728.00',
    priceDown: true,
  },
  {
    id: 6,
    name: 'Ethereum',
    unit: 'ETH',
    textColor: '#5A14B5',
    backgroundColor: '#D1D2F0',
    image: require('../assets/images/crypto/ethereum.png'),
    inactiveimage: require('../assets/images/crypto/ethereumInactive.png'),
    avatar: require('../assets/images/avatars/girl3.png'),
    price: '55728.00',
    priceDown: false,
  },
  {
    id: 7,
    name: 'Cardano',
    unit: 'ADA',
    textColor: '#1454B5',
    backgroundColor: '#D1DAF0',
    image: require('../assets/images/crypto/cardano.png'),
    inactiveimage: require('../assets/images/crypto/cardanoInactive.png'),
    avatar: require('../assets/images/avatars/boy2.png'),
    price: '55728.00',
    priceDown: true,
  },

  {
    id: 8,
    name: 'Cronos',
    unit: 'CRO',
    textColor: '#145EB5',
    backgroundColor: '#D1E7F0',
    image: require('../assets/images/crypto/cronos.png'),
    inactiveimage: require('../assets/images/crypto/cronosInactive.png'),
    avatar: require('../assets/images/avatars/boy3.png'),
    price: '55728.00',
    priceDown: false,
  },
];
