export const TRANSFER_TRANSACTION = [
  {
    id: 1,
    type: 'transfer',
    title: 'Adebambo Salako',
    subTitle: 'Outbound-Transfer',
    amount: '7600.00',
    image: require('../assets/images/banks/kudaBank.png'),
    flow: 'out',
  },
  {
    id: 2,
    type: 'topUp',
    title: 'Wallet Top-up',
    subTitle: 'Withdraw',
    amount: '50034.75',
    image: require('../assets/images/others/withdrawalButton.png'),
    flow: 'in',
  },

  {
    id: 3,
    type: 'transfer',
    title: 'Adebambo Salako',
    subTitle: 'Outbound-Transfer',
    amount: '7600.00',
    image: require('../assets/images/banks/kudaBank.png'),
    flow: 'out',
  },
  {
    id: 4,
    type: 'topUp',
    title: 'Wallet Top-up',
    subTitle: 'Withdraw',
    amount: '50034.75',
    image: require('../assets/images/others/withdrawalButton.png'),
    flow: 'in',
  },
  {
    id: 5,
    type: 'transfer',
    title: 'Adebambo Salako',
    subTitle: 'Outbound-Transfer',
    amount: '7600.00',
    image: require('../assets/images/banks/kudaBank.png'),
    flow: 'out',
  },
];
export const BILLS_TRANSACTION = [
  {
    id: 1,
    type: 'tv',
    title: 'DStv Premium',
    subTitle: '77936636637',
    amount: '7600.00',
    image: require('../assets/images/tvs/dstv.png'),
  },
  {
    id: 2,
    type: 'network',
    title: 'Data Subscription',
    subTitle: 'MTN 30GB',
    amount: '7600.00',
    image: require('../assets/images/networks/mtn.png'),
  },
  {
    id: 3,
    type: 'network',
    title: 'Data Subscription',
    subTitle: 'MTN 30GB',
    amount: '7600.00',
    image: require('../assets/images/networks/mtn.png'),
  },
  {
    id: 4,
    type: 'tv',
    title: 'DStv Premium',
    subTitle: '77936636637',
    amount: '7600.00',
    image: require('../assets/images/tvs/dstv.png'),
  },
  {
    id: 5,
    type: 'network',
    title: 'Data Subscription',
    subTitle: 'MTN 30GB',
    amount: '7600.00',
    image: require('../assets/images/networks/mtn.png'),
  },
];
export const CRYPTO_TRANSACTION = [
  {
    id: 1,
    type: 'crypto',
    title: 'Bitcoin',
    subTitle: 'Sold - $250',
    amount: '150090.20',
    image: require('../assets/images/crypto/bitcoin.png'),
    coin: 'btc',
  },
  {
    id: 2,
    type: 'crypto',
    title: 'USDT',
    subTitle: '$100-500',
    amount: '7600.00',
    image: require('../assets/images/crypto/tether.png'),
    coin: 'usdt',
  },
  {
    id: 3,
    type: 'crypto',
    title: 'Bitcoin',
    subTitle: 'Sold - $250',
    amount: '150090.20',
    image: require('../assets/images/crypto/bitcoin.png'),
    coin: 'btc',
  },
  {
    id: 4,
    type: 'crypto',
    title: 'Bitcoin',
    subTitle: 'Sold - $250',
    amount: '150090.20',
    image: require('../assets/images/crypto/bitcoin.png'),
    coin: 'btc',
  },
  {
    id: 5,
    type: 'crypto',
    title: 'Ethereum',
    subTitle: 'Sold - $250',
    amount: '150090.20',
    image: require('../assets/images/crypto/ethereum.png'),
    coin: 'eth',
  },
];
export const GIFT_CARD_TRANSACTION = [
  {
    id: 1,
    type: 'giftcard',
    title: 'Amazon',
    subTitle: 'UK Amazon $100-500',
    amount: '7600.00',
    image: require('../assets/images/giftcard/amazon.png'),
    flow: 'in',
  },
  {
    id: 2,
    type: 'giftcard',
    title: 'Apple',
    subTitle: 'E-Code Itunes $50-200',
    amount: '7600.00',
    image: require('../assets/images/giftcard/apple.png'),
    flow: 'in',
  },
  {
    id: 3,
    type: 'giftcard',
    title: 'BestBuy',
    subTitle: 'UK BestBuy $100-500',
    amount: '7600.00',
    image: require('../assets/images/giftcard/bestBuy.png'),
    flow: 'in',
  },
  {
    id: 4,
    type: 'giftcard',
    title: 'Ebay',
    subTitle: 'UK Ebay $100-500',
    amount: '7600.00',
    image: require('../assets/images/giftcard/ebay.png'),
    flow: 'in',
  },
  {
    id: 5,
    type: 'giftcard',
    title: 'BestBuy',
    subTitle: 'UK BestBuy $100-500',
    amount: '7600.00',
    image: require('../assets/images/giftcard/bestBuy.png'),
    flow: 'out',
  },
];
